---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: machine.docker
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - docker 
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

provisioner:
  name: ansible
verifier:
  name: ansible
