---
dependency:
  name: galaxy
driver:
  name: docker
platforms:      
  - name: machine.nodocker
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    groups:
      - nodocker 
    pre_build_image: true
    
provisioner:
  name: ansible
verifier:
  name: ansible
