---
name: Lint and Test

'on':
  push:
    branches:
      - 'master'
    tags-ignore:
      - '**'

jobs:

  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          VALIDATE_JSCPD: false

  sandbox:
    name: Sandbox Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Run molecule Tests
        run: |
          rm -rf .env
          pip3 install --upgrade --force-reinstall virtualenv
          python3 -m virtualenv .env
          source .env/bin/activate
          pip install -r requirements.txt
          #ansible-galaxy install -r requirements.yml -f
          python -V
          pip -V
          ansible --version
          molecule test --all
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1